### PR TITLE
Create dialog.md

### PR DESCRIPTION
**Pull request by Erazias**

### CODE REVIEW

**Review by FloofyPlasma — CHANGES_REQUESTED** [review]
Please add your new page to the objects index.

**Comment by Erazias** [comment]
> Please add your new page to the objects index.

Can I ask what you mean by this?

**Comment by FloofyPlasma** [comment]
See file [objects/objects-index.md]

**Comment by Erazias** [comment]
> See file [objects/objects-index.md]

I wasn't sure if I could do it through here, so I instead made another pull request: https://github.com/retro-dev-rblx/Docs/pull/10

**Review by Erazias — COMMENTED** [review]
/

**Pull request closed without merging**
