### PR TITLE
tell where to contribute

### PR DESCRIPTION
**Pull request by quadsYT**
:troll~1:

# tell where to contribute

My pull request is to
work on home page

# Additional information

this is so that you can easily find the github on the wiki

### CODE REVIEW

**Comment by klafl6401** [comment]
Get out of here noob

**Comment by quadsYT** [comment]
:trollface:

**Comment by Ceqell** [comment]
> :troll~1:
> 
> # tell where to contribute
> My pull request is to work on home page
> 
> # Additional information
> this is so that you can easily find the github on the wiki

https://github.com/firstcontributions/first-contributions

i recommend looking at this tutorial and the github desktop tutorial linked at the bottom too 

additional info on how you can start contributing (not my video)

https://www.youtube.com/watch?v=CML6vfKjQss

**Comment by FloofyPlasma** [comment]
I do not see a purpose for this as all pages have an "Edit on Github" button.
image
Screenshot 2023-07-16 at 12 56 14 PM

**Pull request closed without merging**
